"""
Django settings for project_view project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/dev/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'txa!of_4!fq6#ueey2*m6vo8ik+7jct&in8^50hqt$(ldfw+uc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'user.apps.UserConfig',
    'cookie.apps.CookieConfig',
    'pro_response.apps.ProResponseConfig',
    'ajax.apps.AjaxConfig',
    'post_app.apps.PostAppConfig',
    'get_app.apps.GetAppConfig',
    'm_http.apps.MHttpConfig',
    'employee.apps.EmployeeConfig',
    'blog.apps.BlogConfig',
    'articles.apps.ArticlesConfig',
    'rs.apps.RsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'project_view.middleware.LoggerMiddleware',
    # 'project_view.middleware.TestMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'project_view.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project_view.wsgi.application'


# Database
# https://docs.djangoproject.com/en/dev/ref/settings/#databases

DATABASES = {
    'default': {
        # 数据库类型
        'ENGINE': 'django.db.backends.mysql',
        # 数据库名称
        'NAME': 'db_orm',
        # 用户
        'USER': 'root',
        # 密码
        'PASSWORD': '123456',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'ATOMIC_REQUESTS': True,
    }
}


# Password validation
# https://docs.djangoproject.com/en/dev/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/dev/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/dev/howto/static-files/

STATIC_URL = '/static/'


# 使用的缓存别名（默认内存缓存）
SESSION_CACHE_ALIAS = 'default'

SESSION_COOKIE_AGE = 3600 # 默认两周单位秒
SESSION_COOKIE_DOMAIN = 'shsxt.com' # session cookie域名 默认没有设置就是当前域名
SESSION_COOKIE_HTTPONLY = False # 设置session cookie是httponly
SESSION_COOKIE_NAME = 'sessionId' # session cookie的名字
SESSION_COOKIE_PATH = '/' #  session cookie的path
SESSION_COOKIE_SECURE = False # session cookie的secure
SESSION_ENGINE = 'django.contrib.sessions.backends.db' # session存贮位置默认db
# 'django.contrib.sessions.backends.db'
# 'django.contrib.sessions.backends.file'
# 'django.contrib.sessions.backends.cache'
# 'django.contrib.sessions.backends.cached_db'
# 'django.contrib.sessions.backends.signed_cookies'
SESSION_EXPIRE_AT_BROWSER_CLOSE = False # 浏览器关闭后是否过期session，默认是False
SESSION_FILE_PATH = 'C://sessions/' #默认没有，就是选择session存储是file时设置的存储位置
# 浏览器刷新时session是否重新计算过期时间，
# 比如设置10分钟过期，那如果为True，每次刷新session都是重新计算时间，
# 如果为False就是10分钟后就过期不管你刷不刷新
SESSION_SAVE_EVERY_REQUEST = False
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer' # session序列化类型
# 'django.contrib.sessions.serializers.PickleSerializer'
# 'django.contrib.sessions.serializers.JSONSerializer'
