# Generated by Django 2.2 on 2018-08-03 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=18)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(db_column='user_name', max_length=20, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('slugUrl', models.SlugField(db_column='slug_url', default='')),
                ('header', models.CharField(max_length=255)),
                ('age', models.IntegerField(db_column='age', default=0)),
            ],
        ),
        migrations.AddField(
            model_name='usercontact',
            name='userInfo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo'),
        ),
    ]
